### PR TITLE
Add linking to key features

### LINKED ISSUE #69: Feature Request: Make "keyfeatures" cards linkable
I think it would be a nice feature to allow the `keyfeatures` cards to link to other internal or external pages.

The hugo fresh theme has something similar: see the cards under the "Great Power Comes" section: https://hugo-fresh.vercel.app/ (though I think making the entire card clickable is preferable to adding a button; this is a minor detail though).

### PR DESCRIPTION
**Pull request by stefanv**
When a key feature has a link it will:

- Light up when hovering over it
- Have an animated line underneath it
- Have a clickable (hand) pointer

The other cards will be static.

Closes #69

### CODE REVIEW

**Review by rossbar — APPROVED** [review]
I tried this out in rossbar/manual.scientific-python.org-hugo#5 (haven't setup preview yet) and it works exactly as I'd hoped. Tested there with a relative URL to an internal page to compliment the example here with the external link - works as expected :rocket:

**Comment by stefanv** [comment]
We don't have a use-case for this now, so closing until it comes up again.

**Comment by jarrodmillman** [comment]
I have a potential use case, so want to check this out.  May want slightly different look / behavior.  Will add more later.

**Comment by jarrodmillman** [comment]
See #147.

**Comment by jarrodmillman** [comment]
See https://github.com/scientific-python/learn.scientific-python.org/pull/3.

**Pull request closed without merging**
