### PR TITLE
UI fixes

### PR DESCRIPTION
**Pull request by VedantBhawsar**

### CODE REVIEW

**Comment by jarrodmillman** [comment]
Could you explain a bit about why you are making these changes? What does it fix?

Also, please revert your white space changes.

**Comment by tupui** [comment]
Also remember to have a look at how it looks on mobile.

**Comment by VedantBhawsar** [comment]
> Could you explain a bit about why you are making these changes? What does it fix?

- I have change the width of home screen button `cta-button` to looks better.
- Fixed some Alignment issues in footer 
- make `SCIENTIFIC DOMAINS` section compatible with mobile view it's overflowing before.

**Comment by alphapapa** [comment]
I pushed some commits that remove whitespace-only changes and tidy the indentation of the new changes.  Here are before-and-after screenshots:


<details><summary>Current main:</summary>
<p>

theme scientific-python org_


</p>
</details> 
<details><summary>This PR:</summary>
<p>

deploy-preview-248--scientific-python-hugo-theme netlify app_


</p>
</details> 

On a Pixel 5-size screen:

<details><summary>Current main:</summary>
<p>

theme scientific-python org_(Pixel 5)


</p>
</details> 

<details><summary>This PR:</summary>
<p>

deploy-preview-248--scientific-python-hugo-theme netlify app_(Pixel 5)


</p>
</details> 

@VedantBhawsar 

> > Could you explain a bit about why you are making these changes? What does it fix?
> 
> * I have change the width of home screen button `cta-button` to looks better.

I don't see a difference in this, so maybe that was already fixed outside of this PR.

> * Fixed some Alignment issues in footer

I don't see any changes in that, so maybe they were already fixed outside of this PR.

> * make `SCIENTIFIC DOMAINS` section compatible with mobile view it's overflowing before.

I'm not sure what section you mean.  I don't see any overflowing in the Pixel 5-sized viewport.

There are also some other changes in the PR that I'm not sure the purpose of, like:

* https://github.com/scientific-python/scientific-python-hugo-theme/pull/248/files#diff-7df60224d9482f17c42fd4be434599a1c7b88e2008e16b022e24629e0d95435bL56-L61
* https://github.com/scientific-python/scientific-python-hugo-theme/pull/248/files#diff-86f5cd14baae584bbd84e52ed87063a147bad0129962bde580d4eb0ce936e1d4L310-L315

If you could explain those, that would be helpful.  Thanks.

**Review by bsipocz — COMMENTED** [review]
The social media icons in the footnote in the "this PR" screenshot doesn't look right.

Also, I think the logo in the title line is not supposed to be shrunk for the desktop version.

**Comment by alphapapa** [comment]
@bsipocz Yeah, this PR seems to be based on an outdated commit.  I'm trying to figure out if there's anything in this PR that can be helpfully applied on top of the current code.  Hopefully @VedantBhawsar will reply; if not, we can probably close tihs.

**Pull request closed without merging**
