### PR TITLE
Remove jquery

### PR DESCRIPTION
**Pull request by jarrodmillman**
I think this should be good to go.

### CODE REVIEW

**Review by tupui — APPROVED** [review]
Will definitely help to speed things 👍 if we don't need it later then perfect.

**Comment by stefanv** [comment]
I'll take a look at how to fix the shortcuts.

**Comment by stefanv** [comment]
Jquery is being used in fresh.js and shortcuts.js quite extensively, so it will take a bit more work to get rid of it.

**Comment by stefanv** [comment]
The simplest solution for now may be to replace jquery with its slim build, https://code.jquery.com/jquery-3.6.0.slim.min.js, which is 70KB.

**Pull request merged**
