### PR TITLE
Remove uikit

### PR DESCRIPTION
**Pull request by jarrodmillman**
May still need this for numpy.org (need to check).  There are more issues to fix, so this isn't ready to merge.

- [ ] font spacing / weight
- [ ] paragraph spacing (not as much as before and more space below headers)
- [ ] feature (font / paragraph spaces?)
- [x] tt text (font weight / color)
- [x] border and background for code blocks

### CODE REVIEW

**Comment by stefanv** [comment]
Comparing:

https://deploy-preview-94--scientific-python-hugo-theme.netlify.app/
https://theme.scientific-python.org/

The only thing I notice is that text moves around a little bit, but more importantly that the footer icon colors change. That should be a small CSS adjustment to fix.

**Comment by jarrodmillman** [comment]
screenshot

**Comment by stefanv** [comment]
I'm not 100% sure what you're showing in that screenshot—this is not what I see on my screen (in yours, icons are missing and fonts seem to be in the same places).

**Comment by jarrodmillman** [comment]
There is also a spacing issue (e.g., codeblocks) that @stefanv noticed.

**Pull request merged**
