### PR TITLE
Refactor bulma navbar css

### PR DESCRIPTION
**Pull request by jarrodmillman**

### CODE REVIEW

**Comment by stefanv** [comment]
I think now that we have only one navbar, we may be able to get rid of the transparent classes?

**Comment by jarrodmillman** [comment]
I am going to do this in several stages to make it easier to follow. I will also try to get rid of is-fresh. And then move everything into navbar.css.

**Comment by stefanv** [comment]
Thanks, Jarrod! I noticed an (existing) artifact, which is that when you switch between light and dark mode, the navbar fades in. Yet another animation to get rid of!

**Comment by stefanv** [comment]
The hamburger bar menu highlight also changed (or, at least, is different from what I see now on scipy.org). I'll let you decide whether that's important to keep or not; go ahead an merge otherwise.

**Pull request merged**
