### PR TITLE
Add plausible analytics

### PR DESCRIPTION
**Pull request by stefanv**
Closes https://github.com/scientific-python/scientific-python-hugo-theme/issues/15

### CODE REVIEW

**Comment by jarrodmillman** [comment]
@stefanv The CI should pass if you rebase on main.

**Comment by tupui** [comment]
Considering all projects involved, it could almost make sense to build and host our own proxy (there are nodes with unlimited bandwidth available for less than $100/month on some platforms). Was there any discussion about that?

**Comment by stefanv** [comment]
That's what we have; projects can just ask us, and we can add them.

**Comment by stefanv** [comment]
@tupui See https://github.com/scientific-python/scientific-python-hugo-theme/pull/89/files#diff-d1b9763f2fd69c5bf0c8f0c2bd533c169f138d2f605b64a610a5a2fc59ec07d4R104

**Comment by tupui** [comment]
> That's what we have; projects can just ask us, and we can add them.

Oh great! I will link this to the issue in SciPy then 😃

**Pull request merged**
