### PR TITLE
Prepare for better PST alignment

### PR DESCRIPTION
**Pull request by jarrodmillman**

### CODE REVIEW

**Comment by stefanv** [comment]
Spacing under code highlighted section:

image

**Comment by stefanv** [comment]
Menu font size should be smaller than text font:

image

image

**Comment by stefanv** [comment]
Not sure what (if anything) to do about it, but headers with `pre` look strange with the boxes around them. Maybe for headers turn off boxes? I don't think there are any examples of this in PDST:

image

**Comment by stefanv** [comment]
When reloading this page, the page flashes light mode and then goes dark:

https://deploy-preview-329--scientific-python-hugo-theme.netlify.app/examples/kitchen-sink/

(I have dark mode enabled by default.)

**Comment by stefanv** [comment]
Could we render kitchen sink straight into /examples? Otherwise, it takes two clicks to get there: https://deploy-preview-329--scientific-python-hugo-theme.netlify.app/examples/

**Comment by stefanv** [comment]
Here we're still using the old typography for the heading:

image

**Comment by stefanv** [comment]
PDST H6 header and text:

image

Our H6 header and text:

image

**Comment by stefanv** [comment]
I aligned the title rendering with PDST, but now there is a gap between the title and text to take care of. Classes `.title` and `.section-title` may also need to be removed from our CSS.

**Comment by jarrodmillman** [comment]
Following on @stefanv comment on the font for the shortcuts, I would like them to follow the pydata-sphinx-theme (pst). In addition to the size being smaller, there are likely other issues.

For example, code literals aren't rendered correctly. Here is what the look like with this PR:
2023-10-28T00:25:52,206824201-07:00

Here is how they look on the pydata site:
2023-10-28T00:22:19, 915580831-07:00

This is a separate issue, but I would also like to have the breadcrumbs like pst. And we should consider whether we want to have a section navigation and move on-this-page navigation to the right when we do. If the homepages don't have a lot of text it makes sense to just have an on-this-page navigation. But, for the development guide (https://learn.scientific-python.org/development/) it will need a site navigation menu. That site doesn't currently have on-this-page navigation, but I think it should. Anyway, we can deal with that when we port the development guide over.

**Comment by jarrodmillman** [comment]
> Could we render kitchen sink straight into /examples? Otherwise, it takes two clicks to get there: https://deploy-preview-329--scientific-python-hugo-theme.netlify.app/examples/

We could but that is going to make future PRs more tricky, I think. Some PRs will add to the kitchen sink and some will add to the same level as kitchen sink under examples. This PR is intend mainly to set up the infrastructure for several future PRs. We could I suppose just develop off this PR and leave the main branch alone. Then people could make PRs against my branch.

**Comment by jarrodmillman** [comment]
> Not sure what (if anything) to do about it, but headers with `pre` look strange with the boxes around them. Maybe for headers turn off boxes? I don't think there are any examples of this in PDST:

This is what pydata-sphinx-theme does (see above).

**Comment by stefanv** [comment]
I think I addressed most of the remaining concerns:

* d1de9a9 Align title rendering with PDST
* f8044fb Move shortcuts to right side, as in PDST
* 80338e5 Move kitchen sink directly into examples
* 0d63ee2 Render literals in shortcuts
* 86291c0 Reduce shortcuts text size
* 9fec120 Add breadcrumbs

**Comment by stefanv** [comment]
The fix that I had for spacing out two headers in a row (document that starts with h1 h2 headers didn't quite pan out. Leaving that for another PR.

**Comment by stefanv** [comment]
Reminder to self: update docs that explain how to generate themes.

**Comment by jarrodmillman** [comment]
```
git switch kitchen-sink-admonitions
git reset --hard 5b4e60c

git reset --hard 2087d46
git reset 21973c1
git add -u
git add doc/content/examples/_index.md doc/content/examples/kitchen-sink/_index.md
git commit --amend

git cherry-pick 690dbbb
git cherry-pick 5870fec
git cherry-pick f49cad7
git cherry-pick 27a9612
git cherry-pick ab13d16
git cherry-pick 22ed707
git cherry-pick 79fb314
git cherry-pick de8b24c
git cherry-pick 221d7d7

git cherry-pick be725e2
git cherry-pick e2930b2

git reset --soft HEAD~2
git commit -m "Improve title rendering"

git cherry-pick a447aae
git cherry-pick d089b5f
git cherry-pick 4393f5f
git cherry-pick 29c54da
git cherry-pick db87e11
git cherry-pick 891c892
git cherry-pick 5b4e60c

git push -f jarrod kitchen-sink-admonitions
```

**Review by stefanv — APPROVED** [review]

**Pull request merged**
