### PR TITLE
Fix hero title and icon alignment on narrower screens

### PR DESCRIPTION
**Pull request by alphapapa**
This PR is a WIP that is intended to improve several issues as more commits are made.

### CODE REVIEW

**Comment by alphapapa** [comment]
https://github.com/scientific-python/scientific-python-hugo-theme/pull/276/commits/764ccd948b053eb50adec3cfd243b878db5b93b6 screenshots:

<details><summary>Screenshots</summary>
<p>
Before: 

localhost_1313_(iPad Air)


After: 

localhost_1313_(iPad Air) (1)


</p>
</details>

**Comment by stefanv** [comment]
The text in the before looks okay to me; the thing we want to prevent is the logo drifting too far out.

At certain zoom levels, you get this (using this PR):

image

**Comment by alphapapa** [comment]
> The text in the before looks okay to me; the thing we want to prevent is the logo drifting too far out.
> 
> At certain zoom levels, you get this (using this PR):

Thanks, now I understand better.  The commit I just pushed looks like this now:

<details><summary>Details</summary>
<p>

localhost_1313_ (1)
localhost_1313_ (2)
localhost_1313_ (3)
localhost_1313_


</p>
</details> 

I'd still like to make sure the "GITHUB" button doesn't run up against the right edge, but please let me know if this solves the text/icon alignment the way you were wanting.

**Comment by stefanv** [comment]
That looks better!  Scientific Python itself is a bit of an outlier, since we probably want the logo to be attached to the Python part. But I think for most projects what you have now is reasonable.

**Comment by alphapapa** [comment]
Rebased on `main`.  The current screenshots look like this:

<details><summary>Details</summary>
<p>

localhost_1313_ (1)
localhost_1313_ (2)
localhost_1313_


</p>
</details> 

I think this is ready to merge.

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
